name: protos
description: A starting point for Dart libraries or applications.
version: 1.0.0


environment:
  sdk: ^3.1.0


dependencies:
  grpc: ^3.2.3
  protobuf: ^3.1.0
  protoc_plugin: ^21.1.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
