# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drone_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64rone_service.proto\x12\x05\x64rone\"!\n\rStatusRequest\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\x05\"B\n\x0eStatusResponse\x12\x19\n\x04mode\x18\x01 \x01(\x0e\x32\x0b.drone.Mode\x12\x15\n\rbattery_level\x18\x02 \x01(\x02\"D\n\x11\x43hangeModeRequest\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12\x1d\n\x08new_mode\x18\x02 \x01(\x0e\x32\x0b.drone.Mode\"?\n\rChargeRequest\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12\x1c\n\x14target_battery_level\x18\x02 \x01(\x02\"2\n\x0eSimpleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"B\n\x0e\x43hargeResponse\x12\x15\n\rbattery_level\x18\x01 \x01(\x02\x12\x19\n\x11\x63harging_complete\x18\x02 \x01(\x08*7\n\x04Mode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04\x41UTO\x10\x01\x12\n\n\x06MANUAL\x10\x02\x12\x0c\n\x08\x43HARGING\x10\x03\x32\xbf\x02\n\x0c\x44roneService\x12\x38\n\tGetStatus\x12\x14.drone.StatusRequest\x1a\x15.drone.StatusResponse\x12@\n\x0fGetStatusStream\x12\x14.drone.StatusRequest\x1a\x15.drone.StatusResponse0\x01\x12=\n\nChangeMode\x12\x18.drone.ChangeModeRequest\x1a\x15.drone.SimpleResponse\x12\x35\n\x06\x43harge\x12\x14.drone.ChargeRequest\x1a\x15.drone.SimpleResponse\x12=\n\x0c\x43hargeStream\x12\x14.drone.ChargeRequest\x1a\x15.drone.ChargeResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drone_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MODE']._serialized_start=388
  _globals['_MODE']._serialized_end=443
  _globals['_STATUSREQUEST']._serialized_start=30
  _globals['_STATUSREQUEST']._serialized_end=63
  _globals['_STATUSRESPONSE']._serialized_start=65
  _globals['_STATUSRESPONSE']._serialized_end=131
  _globals['_CHANGEMODEREQUEST']._serialized_start=133
  _globals['_CHANGEMODEREQUEST']._serialized_end=201
  _globals['_CHARGEREQUEST']._serialized_start=203
  _globals['_CHARGEREQUEST']._serialized_end=266
  _globals['_SIMPLERESPONSE']._serialized_start=268
  _globals['_SIMPLERESPONSE']._serialized_end=318
  _globals['_CHARGERESPONSE']._serialized_start=320
  _globals['_CHARGERESPONSE']._serialized_end=386
  _globals['_DRONESERVICE']._serialized_start=446
  _globals['_DRONESERVICE']._serialized_end=765
# @@protoc_insertion_point(module_scope)
